# Generated by Django 5.0.7 on 2024-07-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('codcli', models.CharField(max_length=10)),
                ('nomecli', models.CharField(max_length=100)),
                ('razasoccli', models.CharField(max_length=100)),
                ('datacli', models.DateField()),
                ('cnpjcli', models.CharField(max_length=20)),
                ('fonecli', models.CharField(max_length=20)),
                ('cidcli', models.CharField(max_length=50)),
                ('estcli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesBkp',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('codcli', models.CharField(max_length=10)),
                ('nomecli', models.CharField(max_length=100)),
                ('razasoccli', models.CharField(max_length=100)),
                ('datacli', models.DateField()),
                ('cnpjcli', models.CharField(max_length=20)),
                ('fonecli', models.CharField(max_length=20)),
                ('cidcli', models.CharField(max_length=50)),
                ('estcli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('idforn', models.AutoField(primary_key=True, serialize=False)),
                ('codiforn', models.CharField(max_length=10)),
                ('nomeforn', models.CharField(max_length=100)),
                ('razasocforn', models.CharField(max_length=100)),
                ('foneforn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvende', models.AutoField(primary_key=True, serialize=False)),
                ('codivende', models.CharField(max_length=10)),
                ('nomevende', models.CharField(max_length=100)),
                ('razasocvende', models.CharField(max_length=100)),
                ('fonevende', models.CharField(max_length=20)),
                ('porcvende', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idprod', models.AutoField(primary_key=True, serialize=False)),
                ('codiprod', models.CharField(max_length=20)),
                ('descprod', models.CharField(max_length=100)),
                ('valorprod', models.FloatField()),
                ('situprod', models.CharField(max_length=1)),
                ('idforn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvend', models.AutoField(primary_key=True, serialize=False)),
                ('codivend', models.CharField(max_length=10)),
                ('valorvend', models.FloatField()),
                ('descvend', models.FloatField()),
                ('totalvend', models.FloatField()),
                ('datavend', models.DateField()),
                ('valorcomissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.cliente')),
                ('idforn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.fornecedor')),
                ('idvende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('iditvend', models.AutoField(primary_key=True, serialize=False)),
                ('valoritvend', models.FloatField()),
                ('qtditvend', models.IntegerField()),
                ('descitvend', models.FloatField()),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.produto')),
                ('idvend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.venda')),
            ],
        ),
    ]
