# Generated by Django 5.0.7 on 2024-07-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBkp',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('codcli', models.CharField(max_length=10)),
                ('nomecli', models.CharField(max_length=100)),
                ('razasoccli', models.CharField(max_length=100)),
                ('datacli', models.DateField()),
                ('cnpjcli', models.CharField(max_length=20)),
                ('fonecli', models.CharField(max_length=20)),
                ('cidcli', models.CharField(max_length=50)),
                ('estcli', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientesbkp',
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('iditvend', models.AutoField(primary_key=True, serialize=False)),
                ('valoritvend', models.FloatField()),
                ('qtditvend', models.IntegerField()),
                ('descitvend', models.FloatField()),
            ],
            options={
                'db_table': 'itensvenda',
            },
        ),
        migrations.DeleteModel(
            name='ClientesBkp',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='venda',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='vendedor',
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='idprod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.produto'),
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='idvend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.venda'),
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
    ]
